[package]
name = "verwalter"
description = """
    Decentralized resource and configuration management daemon
"""
readme = "README.rst"
keywords = ["cluster", "linux", "resource", "configuration", "management"]
version = "0.1.0"
homepage = "http://github.com/tailhook/verwalter"
documentation = "http://verwalter.readthedocs.org"
authors = ["Paul Colomiets <paul@colomiets.name>"]

[dependencies]
rotor = "0.4.0"
rotor-stream = "0.3.0"
rotor-http = "0.4.0"
lua = { rev="e76065b", git = "https://github.com/jcmoyer/rust-lua53" }
quick-error = "0.2.1"
liquid = "0.2"
argparse = "0.2"
handlebars = "0.12"
log = "0.3.2"
env_logger = "0.3.1"
tempfile = "1.1.1"
rustc-serialize = "0.3.16"
quire = "0.1"
yaml-rust = "0.3"
scan_dir = "0.3"
time = "0.1.32"
rand = "0.3.11"
libc = "0.2"
matches = "0.1.2"
hyper = "0.7"
mio = "0.5"
