[package]
name = "verwalter"
description = """
    Decentralized resource and configuration management daemon
"""
readme = "README.rst"
keywords = ["cluster", "linux", "resource", "configuration", "management"]
version = "0.1.7"
homepage = "http://github.com/tailhook/verwalter"
documentation = "http://verwalter.readthedocs.org"
authors = ["Paul Colomiets <paul@colomiets.name>"]

[dependencies]
rotor = "0.6.3"
rotor-http = { rev="feaf6af", git="git://github.com/tailhook/rotor-http" }
rotor-tools = { rev="f7989a2", git="git://github.com/tailhook/rotor-tools" }
rotor-cantal = { rev="f772b26", git="git://github.com/tailhook/rotor-cantal" }
lua = { rev="9ff093b", git = "https://github.com/tailhook/rust-lua53" }
quick-error = "0.2.1"
liquid = "0.2"
argparse = "0.2"
handlebars = "0.15"
log = "0.3.2"
env_logger = "0.3.1"
tempfile = "1.1.1"
rustc-serialize = "0.3.16"
quire = "0.1"
yaml-rust = "0.3"
scan_dir = "0.3"
time = "0.1.32"
rand = "0.3.11"
libc = "0.2"
matches = "0.1.2"
hyper = "0.7"
mio = "0.5"
nix = "0.5.0"
cbor-codec = "0.4.2"
regex = "0.1.58"
lazy_static = "0.1.15"
sha1 = "0.1.1"

[[bin]]
name = "verwalter"
