[package]
name = "verwalter"
description = """
    Decentralized resource and configuration management daemon
"""
readme = "README.rst"
keywords = ["cluster", "linux", "resource", "configuration", "management"]
version = "0.1.0"
homepage = "http://github.com/tailhook/verwalter"
documentation = "http://verwalter.readthedocs.org"
authors = ["Paul Colomiets <paul@colomiets.name>"]

[dependencies]
rotor = "0.2"
rotor-http = "0.2.1"
hlua = "0.1.6"
quick-error = "0.1.3"
liquid = "0.1.1"
argparse = "0.2.0"
handlebars = "0.10.1"
log = "*"
env_logger = "0.3.1"
tempfile = "1.1.1"
rustc-serialize = "0.3.16"
quire = { git = "git://github.com/tailhook/rust-quire" }
yaml-rust = "0.2.2"
scan_dir = "0.2.0"
